name: Build and Deploy Docker Image

on:
  push:
    branches:
      - docker  # 您可以指定要触发的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t dify-webapp:latest .
      - name: Save Docker image
        run: |
          docker save dify-webapp:latest | gzip > dify-webapp.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: dify-webapp
          path: dify-webapp.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 确保构建先完成

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: dify-webapp
          path: .

      - name: Copy Docker image to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # 安装 sshpass 和 pv
          sudo apt-get install -y sshpass pv
          # 使用 pv 显示进度
          pv dify-webapp.tar.gz | sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cat > /tmp/dify-webapp.tar.gz"
          
      - name: Load and run Docker image on server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            docker load < /tmp/dify-webapp.tar.gz
            docker run -d --rm -p 80:3000 --name dify-webapp dify-webapp:latest
          EOF
