name: Build and Deploy Docker Image

on:
  push:
    branches:
      - docker  # 您可以指定要触发的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy Docker image to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'touch /tmp/newfile.txt'
